### ISSUE TITLE
Cannot ipfs start

### ISSUE THREAD

**Issue by MrToph** [diasdavid/ipscend#115]
Hi,
when  I run `ipscend ipfs start` I get the following error:

```
no IPFS repo found, going to start a new one
Error: events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\Name\AppData\Roaming\npm\node_modules\ipscend\node_modules\ipfsd-ctl\node_modules\go-ipfs-dep\go-ipfs\ipfs ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:421:16)
    at internalTickCallback (internal/process/next_tick.js:72:19)
    at process._tickCallback (internal/process/next_tick.js:47:5)
    at Function.Module.runMain (internal/modules/cjs/loader.js:777:11)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
    at startup (internal/bootstrap/node.js:227:5)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
    at onErrorNT (internal/child_process.js:421:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

    at Object.done (C:\Users\Name\AppData\Roaming\npm\node_modules\ipscend\node_modules\ipfsd-ctl\src\exec.js:23:27)
    at Stream.listeners.done.once (C:\Users\Name\AppData\Roaming\npm\node_modules\ipscend\node_modules\ipfsd-ctl\src\exec.js:45:18)
    at Stream.f (C:\Users\Name\AppData\Roaming\npm\node_modules\ipscend\node_modules\once\once.js:25:25)
    at Stream.emit (events.js:189:13)
    at Stream.EventEmitter.emit (domain.js:441:20)
    at Socket.reemit (C:\Users\Name\AppData\Roaming\npm\node_modules\ipscend\node_modules\duplexer\index.js:70:25)
    at Socket.emit (events.js:194:15)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at Pipe._handle.close (net.js:610:12)
```

It seems to fail in `ipfsd-ctl`. I installed the `jsipfs` (ipfs npm package) node. Could it be that I need to use the go-ipfs node?

**Comment by MrToph** [comment]
I did `npm i -g go-ipfs` and then `ipfs init`. If i re-run `ipscend ipfs start`, I now get the following error:

```
starting IPFS daemon (this might take some seconds)
failed to start a daemon
```

But I can run `ipfs daemon` just fine
